name: hearing_test
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  sound_generator: ^0.0.9
  flutter_neumorphic: ^3.0.3
  easy_localization: ^3.0.1
  lottie: ^2.3.2
  headset_connection_event: ^3.0.0
  hooks_riverpod: ^2.3.6
  volume_controller: ^2.0.6

 

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/lottie/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
        

